### ISSUE TITLE
List Index out of range

### ISSUE THREAD

**Issue by e1ace** [hawky358/hass_ids_hyyp#15]
I have the following warning (followed by error) when using the integration. Everything was working fine, but about a week or two ago it stopped and the logs have the following displayed.

**Warning**
```
Logger: homeassistant.config_entries
Source: config_entries.py:959
First occurred: 10:26:56 (1 occurrences)
Last logged: 10:26:56

Config entry 'xxx@gmail.com' for ids_hyyp integration not ready yet: list index out of range; Retrying in background
```
_I have removed my email address_

**Error**
```
Logger: custom_components.ids_hyyp.coordinator
Source: custom_components/ids_hyyp/coordinator.py:35
Integration: IDS Hyyp (hawkMod) ([documentation](https://github.com/hawky358/hass_ids_hyyp))
First occurred: July 24, 2023 at 18:28:12 (1783 occurrences)
Last logged: 10:27:13

Unexpected error fetching ids_hyyp data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ids_hyyp/coordinator.py", line 35, in _async_update_data
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhyypapihawkmod/client.py", line 139, in load_alarm_infos
    return HyypAlarmInfos(self).status()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhyypapihawkmod/alarm_info.py", line 205, in status
    formatted_data: dict[Any, Any] = self._format_data()
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhyypapihawkmod/alarm_info.py", line 121, in _format_data
    _last_notice = self._last_notice()
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhyypapihawkmod/alarm_info.py", line 38, in _last_notice
    _last_notification = self._notifications[0]
                         ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I've tried deleting and resigning in to the integration but it has the same issues.

**Comment by hawky358** [comment]
Hello,

Weird that you don't get any notifications. I can make a hotfix for that, but I am curious as to why you're not getting notifications. Can you please answer below to assist:

- Are you using the ADT or the HYYP "version"
- Which version of the integration are you using?

**Comment by e1ace** [comment]
I'm using Hyyp and I've tried v1.31, v1.33 and the V1.34b2

**Comment by hawky358** [comment]
Very odd. 
There should be no reason that you're not getting notification feedback. Without knowing why exactly it happens it may be difficult to give a fix.
In any event, give 1.3.4-b3 a try.

**Comment by e1ace** [comment]
It works again!

Thanks so much for your help, and efforts in maintaining this dev
