### ISSUE TITLE
HyypApiError

### ISSUE THREAD

**Issue by wernerhp** [hawky358/hass_ids_hyyp#34]
Just an unhandled error.  
I wonder if a persistent notification would be good in case of a failed arm?

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:47:14 (1 occurrences)
Last logged: 21:47:14

[281467540014272] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/ids_hyyp/alarm_control_panel.py", line 93, in async_alarm_disarm
    update_ok = await self.hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhyypapihawkmod/client.py", line 926, in arm_site
    raise HyypApiError(f"Arm site failed: {_json_result['error']}")
pyhyypapihawkmod.exceptions.HyypApiError: Arm site failed: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 290, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
  File "/config/custom_components/ids_hyyp/alarm_control_panel.py", line 102, in async_alarm_disarm
    raise HyypApiError("Cannot disarm alarm") from err
pyhyypapihawkmod.exceptions.HyypApiError: Cannot disarm alarm
```

**Comment by hawky358** [comment]
Thanks, I'll take a look to handle that exception on the HASS side as well.


I don't like the idea of a persistent notification since the IDS server is sometimes "unreliable"
- It sometimes gives a "FAILED" feedback even though it actually armed or disarmed successfully.
- If you're too quick it also states "PENDING" or "FAILED" even though it's successful.

The persistent notifications could then "pile-up" even though nothing's wrong. I personally dislike HASS persistent notifications.

I haven't really bothered trying to fix the issue since the system works "well enough" for me.  I've noticed even the IDS app has the same issue if you try to do too many things to quickly. It doesn't have an "exception" but it sort of times out (becomes stale) until you refresh.

Since it works ok for me I haven't really thought about it, so I don't know what the answer to the issue is. I was considering a refresh of the system even if it "fails". This should give you up-to-date information. Currently it doesn't refresh the alarm status if it failed. 
It doesn't solve the underlying problem, though, but is does show you that the alarm isn't armed.

For me I currently use the push notifications and failure reason sensors to confirm arming. (With the change in armed state)
You can probably write an automation to warn you if it doesn't arm in XX after pushing the button.


If the IDS servers gave more information/feedback it would be easier to create a sensor or warning.

**Comment by hawky358** [comment]
Not sure what I should do with this exception.

Currently it raises this exception when it "thinks" something is wrong. This at least gives feedback that there may be an issue.

I can remove the exception, but then things will "fail" silently.
Persistent notifications aren't great since it can clog up the notifications section, especially if you bypass several zones in quick succession.

For now, the exception seems to be the lesser of the evils in my mind.

Maybe I should remove the exception completely for Zone bypasses, add a persistent notification when there seems to be an arm/disarm failure.

**Comment by wernerhp** [comment]
What if you handle the `HyypApiError` and log as error error instead of exception ao it doesn't include a stack trace, but produces a friendlier "Cannot disarm alarm" erro in the log.  I did something similar in l[ine 200 here](https://github.com/wernerhp/ha.integration.load_shedding/commit/ebeed64c0539ec28a5544ae2d5473c8d5a058c70#diff-931b5f04c9fe29b066faa7ebef9707149db706ed94be6a8dcb7bd339d94a8b65R200)

**Comment by hawky358** [comment]
I've released [1.8.4b1](https://github.com/hawky358/hass_ids_hyyp/tree/1.8.4b1) as a pre-release.

I've changed the way these specific errors are handled by using the Home assistant `ServiceValidationError` .
This keeps the "instant" popup and haptic feedback when something goes wrong, which I like. However, it now only logs a basic error without the stack trace.

"Major" errors like connection problems or protocol errors or something like that should still throw an exception with a full stack trace, but the  "arm failed" or "bypass failed" will now only use the "light" error.

I'll keep this for a bit and see how it goes.
